# Generated by Django 6.0.1 on 2026-02-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subject_studentprofile_tutorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate in currency units', max_digits=10),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='visibility',
            field=models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden')], default='visible', max_length=20),
        ),
    ]
